In [1]:
import numpy as np

In [2]:
# Table 1, Technology (top), Z process (middle) and preference (bottom) configurations
α = .115
κ = 6.667
α_k = -.043
β_k = .04
σ_k = np.array([.00954, 0])

β_z = .056
σ_z = np.array([.022, .05])

δ = .010
η = .032

In [3]:
# Table 2, Steady states for the model specification without climate impacts.
# The values with a superscript were imposed when setting the parameters.
i = .090 # investment capital ratio 
c = .025 # consumption capital ratio
k_growth = -.043 + i - κ/2.*i**2 # capital growth, 0.02

In [4]:
# Table 3, Initial Values
K0 = 695.65
y0 = .540

In [22]:
# Compute consumption numbers, lower triangular covariance matrix
ξ_b = 5.

δ = .01
η = .032

αc_0 = .00484 * 4
αc_1 = .01 * 4
σc = np.array([.00477, 0.]) * 2
αz_1 = .014 * 4
σz = np.array([.011, .025]) * 2

vc = (1-η)/δ
vz = αc_1*vc/(δ+αz_1)
h = -(vz*σz+vc*σc)/ξ_b

In [23]:
σc

array([0.00954, 0.     ])

In [24]:
σz

array([0.022, 0.05 ])

In [15]:
h

array([-0.44282773, -0.58666667])

In [30]:
# Compute consumption numbers, upper triangular covariance matrix

# Refactor covariance matrix
σc = np.array([.00477, 0.]) * 2
σz = np.array([.011, .025]) * 2
var_c = np.dot(σc, σc)
var_z = np.dot(σz, σz)
cov_cz = np.dot(σc, σz)

σz = np.array([0., np.sqrt(var_z)])
σc_2 = cov_cz / σz[1]
σc_1 = np.sqrt(var_c-σc_2**2)
σc = np.array([σc_1, σc_2])

ξ_b = 5.

δ = .01
η = .032

αc_0 = .00484 * 4
αc_1 = .01 * 4
αz_1 = .014 * 4

vc = (1-η)/δ
vz = αc_1*vc/(δ+αz_1)
h = -(vz*σz+vc*σc)/ξ_b

In [31]:
h

array([-0.16905356, -0.71532865])

In [32]:
σc

array([0.00873211, 0.00384213])

In [34]:
σz

array([0.      , 0.054626])

In [35]:
αc_0

0.01936